### PR TITLE
removed symfony 2.8 deprecation warnings

### PR DESCRIPTION
**Pull request by schmeiserd**
https://github.com/qandidate-labs/qandidate-toggle-bundle/pull/16 in a single commit

### CODE REVIEW

**Comment by robertfausk** [comment]
+1 for this

**Comment by othillo** [comment]
this will break on Symfony 2.3 :(
What do you think, @wjzijderveld? 
Separate tags for 2.3?

**Comment by othillo** [comment]
@schmeiserd I've continued on your PR to actually test the specific Symfony versions on Travis CI: https://github.com/qandidate-labs/qandidate-toggle-bundle/pull/19

**Comment by asm89** [comment]
Will be merged in #19.

**Pull request closed without merging**
