### PR TITLE
fix(configuration): complete config tree builder

### PR DESCRIPTION
**Pull request by aurnot**
Hello,

This is a fix of the DI configuration, to allow more toggle configs from yaml.

Cheers!

### CODE REVIEW

**Comment by thewilkybarkid** [comment]
👍  Seems impossible to use `in-set` without this.

**Comment by othillo** [comment]
Thanks for this addition! Do you mind adding unit tests for this?

**Comment by fadoe** [comment]
@othillo What is your idea for a unit test? I looked in the QandidateToggleExtensionTest and had no idea what to do. When you give me a hint I try to add some tests.

**Comment by othillo** [comment]
You can have a look at https://github.com/SymfonyTest/SymfonyConfigTest. I thought it was already a dependency but it's not so I have to admit it's a bit much too ask.

**Comment by fadoe** [comment]
Do you think that it is worth the effort to write the unit test for this?

**Comment by othillo** [comment]
I've create the basic configuration test in https://github.com/qandidate-labs/qandidate-toggle-bundle/pull/63/files.

Let's add similar tests for this PR.

**Comment by fadoe** [comment]
Okay, I will see how it works :-).

**Comment by armetiz** [comment]
This PR allow strategy configuration, which is really useful :)

Can you merge ?

**Pull request closed without merging**
